---
abstract: 'A shortcut to build Moose instances'
author:
  - 'Jed Lund <jandrew@cpan.org>'
build_requires:
  Capture::Tiny: 0.12
  Modern::Perl: 0
  Moose::Role: 0
  MooseX::StrictConstructor: 0
  Test::Moose: 0
  Test::More: 0
  Test::Most: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-ShortCut-BuildInstance
provides:
  Anonymous::Shiras::Moose::Class:
    file: lib/MooseX/ShortCut/BuildInstance.pm
    version: v0.12.2
  MooseX::ShortCut::BuildInstance:
    file: lib/MooseX/ShortCut/BuildInstance.pm
    version: v0.12.2
requires:
  Carp: 0
  Data::Dumper: 0
  Moose: 0
  Moose::Exporter: 0
  Moose::Meta::Class: 0
  Moose::Util: 0
  MooseX::Types::Moose: 0
  Smart::Comments: 0
  perl: 5.010
  version: 0.94
resources:
  bugtracker: https://github.com/jandrew/MooseX-ShortCut-BuildInstance/issues
  homepage: https://github.com/jandrew
  repository: git://github.com///github.com/jandrew/MooseX-ShortCut-BuildInstance.git
version: 0.012.002
