---
abstract: 'A shortcut to build Moose instances'
author:
  - 'Jed Lund <jandrew@cpan.org>'
build_requires:
  Capture::Tiny: 0.12
  Moose::Role: 0
  MooseX::StrictConstructor: 0
  TAP::Formatter::Console: 0
  TAP::Harness: 0
  TAP::Parser::Aggregator: 0
  Test::Moose: 0
  Test::More: 0
  Test::Most: 0
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-ShortCut-BuildInstance
no_index:
  package:
    - Anonymous::Shiras::Moose::Class
    - Test::Role
    - Test::Class
provides:
  MooseX::ShortCut::BuildInstance:
    file: lib/MooseX/ShortCut/BuildInstance.pm
    version: v1.26.2
  MooseX::ShortCut::BuildInstance::Types:
    file: lib/MooseX/ShortCut/BuildInstance/Types.pm
    version: v1.26.2
requires:
  Carp: 0
  Data::Dumper: 0
  Moose: 0
  Moose::Exporter: 0
  Moose::Meta::Class: 0
  Moose::Util: 0
  Smart::Comments: 0
  Type::Library: 0.046
  Type::Utils: 0.046
  Types::Standard: 0.046
  lib: 0
  perl: 5.010
  strict: 0
  version: 0
  warnings: 0
resources:
  bugtracker: https://github.com/jandrew/MooseX-ShortCut-BuildInstance/issues
  homepage: https://github.com/jandrew/MooseX-ShortCut-BuildInstance
  repository: https://github.com/jandrew/MooseX-ShortCut-BuildInstance.git
version: v1.26.2
x_authority: cpan:JANDREW
