---
abstract: 'A shortcut to build Moose instances'
author:
  - 'Jed Lund <jandrew@cpan.org>'
build_requires:
  Capture::Tiny: '0.12'
  Carp: '0'
  Data::Dumper: '0'
  DateTime: '0'
  List::Util: '1.33'
  Moose: '2.1213'
  Moose::Exporter: '0'
  Moose::Meta::Class: '0'
  Moose::Role: '0'
  Moose::Util: '0'
  MooseX::HasDefaults::RO: '0'
  MooseX::StrictConstructor: '0'
  Smart::Comments: '0'
  Test::Moose: '0'
  Test::More: '0'
  Test::Most: '0'
  Type::Tiny: '1.000'
  lib: '0'
  version: '0.77'
configure_requires:
  ExtUtils::MakeMaker: '7.04'
  Moose: '2.1213'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-ShortCut-BuildInstance
no_index:
  package:
    - Anonymous::Shiras::Moose::Class
    - Test::Role
    - Test::Class
    - Mineral
    - Identity
    - Vegetable
provides:
  MooseX::ShortCut::BuildInstance:
    file: lib/MooseX/ShortCut/BuildInstance.pm
    version: v1.34.6
  MooseX::ShortCut::BuildInstance::Types:
    file: lib/MooseX/ShortCut/BuildInstance/Types.pm
    version: v1.34.6
  MooseX::ShortCut::BuildInstance::UnhideDebug:
    file: lib/MooseX/ShortCut/BuildInstance/UnhideDebug.pm
    version: v1.34.6
requires:
  Carp: '0'
  Clone: '0'
  Data::Dumper: '0'
  Moose: '2.1213'
  Moose::Exporter: '0'
  Moose::Meta::Class: '0'
  Moose::Util: '0'
  Type::Library: '0'
  Type::Utils: '1.000'
  Types::Standard: '1.000'
  lib: '0'
  perl: '5.010'
  strict: '0'
  version: '0.77'
  warnings: '0'
resources:
  bugtracker: https://github.com/jandrew/MooseX-ShortCut-BuildInstance/issues
  homepage: https://github.com/jandrew/MooseX-ShortCut-BuildInstance
  repository: https://github.com/jandrew/MooseX-ShortCut-BuildInstance.git
version: v1.34.6
x_authority: cpan:JANDREW
