---
abstract: 'Yet another way to build Moose Classes'
author:
  - 'Jed Lund <jandrew@cpan.org>'
build_requires:
  Modern::Perl: 0
  Moose::Role: 0
  Test::Moose: 0
  Test::More: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Util-ClassBuilder
requires:
  Moose: 0
  Moose::Exporter: 0
  Moose::Meta::Class: 0
  Smart::Comments: 0
  perl: 5.010
  version: 0
version: v0.001_001
